"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_purple)\
$os\
$username\
[](bg:color_fg0 fg:color_purple)\
$directory\
[](fg:color_fg0 bg:color_red)\
$git_branch\
$git_status\
[](fg:color_red bg:color_pastelpurple)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_pastelpurple bg:color_fg1)\
$docker_context\
$conda\
[](fg:color_fg1 bg:color_green)\
$time\
[ ](fg:color_green)\
$line_break$character"""

palette = 'anemos'

[palettes.anemos]
color_fg0 = '#ffffff'
color_fg1 = '#000000'
color_green = '#b8ff12'
color_purple = '#b042ff'
color_pastelpurple = '#e7ddff'
color_darkpurple = '#6204bf'
color_red = '#f24141'

[os]
disabled = false
style = "bg:color_purple fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Kali = ""
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = ""
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_purple fg:color_fg0"
style_root = "bg:color fg:color_fg0"
format = '[  $user ]($style)'

[directory]
style = "fg:color_fg1 bg:color_fg0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_red"
format = '[[ $symbol $branch ](fg:color_fg0 bg:color_red)]($style)'

[git_status]
style = "bg:color_red"
format = '[[($all_status$ahead_behind )](fg:color_fg0 bg:color_red)]($style)'

[nodejs]
symbol = ""
style = "bg:color_pastelpurple"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_pastelpurple)]($style)'

[c]
symbol = " "
style = "bg:color_pastelpurple"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_pastelpurple)]($style)'

[rust]
symbol = ""
style = "bg:color_pastelpurple"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_pastelpurple)]($style)'

[golang]
symbol = ""
style = "bg:color_pastelpurple"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_pastelpurple)]($style)'

[php]
symbol = ""
style = "bg:color_pastelpurple"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_pastelpurple)]($style)'

[java]
symbol = " "
style = "bg:color_pastelpurple"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_pastelpurple)]($style)'

[kotlin]
symbol = ""
style = "bg:color_pastelpurple"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_pastelpurple)]($style)'

[haskell]
symbol = ""
style = "bg:color_pastelpurple"
format = '[[ $symbol( $version) ](fg:color_fg1 bg:color_pastelpurple)]($style)'

[python]
symbol = ""
style = "bg:color_pastelpurple"
format = '[[ ${symbol} (${version})( \($virtualenv\)) ](fg:color_fg1 bg:color_pastelpurple)]($style)'

[docker_context]
symbol = ""
style = "bg:color_fg1"
format = '[[ $symbol( $context) ](fg:color_fg0 bg:color_fg1)]($style)'

[conda]
style = "bg:color_fg1"
format = '[[ $symbol( $environment) ](fg:color_fg0 bg:color_fg1)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_green"
format = '[[  $time ](fg:color_fg1 bg:color_green)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_darkpurple)'
